MiniProyecto_Itla_TV+/Models/ErrorViewModel.cs
namespace MiniProyecto_Itla_TV_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MiniProyecto_Itla_TV+/Controllers/GenerosController.cs
using Application.Interfaces.Servicios;
using Application.ViewModels.Generos;
using Application.ViewModels.Productoras;
using Microsoft.AspNetCore.Mvc;

namespace MiniProyecto_Itla_TV_.Controllers
{
    public class GenerosController : Controller
    {
        private readonly IServiciosGeneros _servicios;

        public GenerosController(IServiciosGeneros servicios)
        {
            _servicios = servicios;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _servicios.ObtenerTodo());
        }


        public IActionResult Create()
        {
            GuardarGenerosViewModel view = new GuardarGenerosViewModel();
            return View(view);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GuardarGenerosViewModel crear)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", crear);
            }

            await _servicios.Agregar(crear);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(int id)
        {
          

            return View("Create", await _servicios.ObtenerPorId(id));
        }

        [HttpPost]

        public async Task<IActionResult> EditPost(GuardarGenerosViewModel editar)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", editar);
            }

            await _servicios.Actualizar(editar);
            return RedirectToAction("Index");
        }




        public async Task<IActionResult> Delete(int id)
        {
            return View(await _servicios.ObtenerPorId(id));
        }


        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _servicios.EliminarPorId(id);
            return RedirectToAction("Index");
        }
    }
}

MiniProyecto_Itla_TV+/Controllers/HomeController.cs
using Application.Interfaces.Servicios;
using Application.ViewModels.Series;
using Microsoft.AspNetCore.Mvc;

namespace MiniProyecto_Itla_TV_.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServiciosSeries _servicios;
        private readonly IServiciosProductoras _serviciosP;
        private readonly IServiciosGeneros _serviciosG;

        public HomeController(IServiciosSeries servicios, IServiciosProductoras serviciosP, IServiciosGeneros serviciosG)
        {
            _servicios = servicios;
            _serviciosG = serviciosG;
            _serviciosP = serviciosP;
        }
        public async Task<IActionResult> Index(FiltroSeriesViewModel vm)
        {
            await _serviciosG.ObtenerTodo();
            
            ViewBag.Productoras = await _serviciosP.ObtenerTodo();
            
            
            return View(await _servicios.ObtenerTodoConFiltro(vm));
        }


        public async Task<IActionResult> Video(int id)
        {            
            return View(await _servicios.ObtenerPorId(id));
        
        }


    }
}

MiniProyecto_Itla_TV+/Controllers/ProductorasController.cs
using Application.Interfaces.Servicios;
using Application.ViewModels.Productoras;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Extensions;

namespace MiniProyecto_Itla_TV_.Controllers
{
    public class ProductorasController : Controller
    {
        private readonly IServiciosProductoras _servicios;

        public ProductorasController(IServiciosProductoras servicios)
        {
            _servicios = servicios;
        }


        public async Task <IActionResult> Index()
        {
            return View(await _servicios.ObtenerTodo());
        }


        public IActionResult Create()
        {
              GuardarProductorasViewModel view =   new GuardarProductorasViewModel();
              return View(view);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GuardarProductorasViewModel crear) {

            if (!ModelState.IsValid)
            {
                return View("Create", crear);
            }

            await _servicios.Agregar(crear);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(int id)
        {

            return View("Create", await _servicios.ObtenerPorId(id));
        }

        [HttpPost]

        public async Task<IActionResult> EditPost(GuardarProductorasViewModel editar)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", editar);
            }

            await _servicios.Actualizar(editar);
            return RedirectToAction("Index");
        }




        public async Task <IActionResult> Delete(int id)
        {         
        return View( await _servicios.ObtenerPorId(id));
        }


        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _servicios.EliminarPorId(id);
            return RedirectToAction("Index");
        }
    }
}

MiniProyecto_Itla_TV+/Controllers/SeriesController.cs
using Application.Interfaces.Servicios;
using Application.ViewModel.Productoras;
using Application.ViewModels.Productoras;
using Application.ViewModels.Series;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MiniProyecto_Itla_TV_.Controllers
{
    public class SeriesController : Controller
    {
        private readonly IServiciosSeries _servicios;
        private readonly IServiciosProductoras _serviciosP;
        private readonly IServiciosGeneros _serviciosG;
        private readonly IServiciosSeriesGeneros _serviciosSeriesGeneros;

        public SeriesController(IServiciosSeries servicios, IServiciosProductoras serviciosP, IServiciosGeneros serviciosG, IServiciosSeriesGeneros serviciosSeriesGeneros)
        {
            _servicios = servicios;
            _serviciosG = serviciosG;
            _serviciosP = serviciosP;
            _serviciosSeriesGeneros = serviciosSeriesGeneros;
        }

        public async Task<IActionResult> Index() 
        {
            await _serviciosG.ObtenerTodo();
            await _serviciosP.ObtenerTodo();
            await _serviciosSeriesGeneros.ObtenerTodo();

            return View(await _servicios.ObtenerTodo());
        }


        public async Task <IActionResult> Create()
        {
            GuardarSeriesViewModel view = new GuardarSeriesViewModel();
         
            view.Productoras = await _serviciosP.ObtenerTodo();
            
            view.Generos = await _serviciosG.ObtenerTodo();
    

            return View(view);
        }

        [HttpPost]
        public async Task<IActionResult> Create(GuardarSeriesViewModel crear)
        {
            if (ModelState.IsValid)
            {
              
                crear.Productoras = await _serviciosP.ObtenerTodo();
                crear.Generos = await _serviciosG.ObtenerTodo();

                return View("Create", crear);
            }

            await _servicios.Agregar(crear);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Edit(int id)
        {
            GuardarSeriesViewModel view = await _servicios.ObtenerPorId(id);
     
            view.Productoras = await _serviciosP.ObtenerTodo();
            view.Generos = await _serviciosG.ObtenerTodo();   
            
            
            
            return View("Create", view);
        }

        [HttpPost]

        public async Task<IActionResult> EditPost(GuardarSeriesViewModel editar)
        {
            if (ModelState.IsValid)
            {
                editar.Productoras = await _serviciosP.ObtenerTodo();
                editar.Generos = await _serviciosG.ObtenerTodo();

                return View("Create", editar);
            }

            await _servicios.Actualizar(editar);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            return View(await _servicios.ObtenerPorId(id));
        }


        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _servicios.EliminarPorId(id);
            return RedirectToAction("Index");
        }
    }
}

MiniProyecto_Itla_TV+/Views/Generos/Create.cshtml
@model Application.ViewModels.Generos.GuardarGenerosViewModel 
@{
    bool modoEditar = Model.Id == 0 ? true : false;
  
}
<div class="row mb-3">

    <h2 class="text-center"> Mantenimiento de Generos  </h2>
</div>

<div class="row">
    <div class="col-4 offset-4">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>@(modoEditar ? "Creando un Genero" : $"Editando Genero: {Model.Nombre}")</h4>
            </div>
            <div class="card-body">

                <form method="POST"  asp-controller="Generos" asp-action="@(modoEditar ? "Create" : "EditPost")">
                    
                    
                    <div class="mb-3">
                        <label class="form-label">Nombre de Generos</label>
                        <input asp-for="Nombre" type="text" class="form-control mb-3" />  
                        <span class="text-danger"asp-validation-for="Nombre"> </span>
                    </div>
                    
                
                    <input type="hidden" asp-for="Id"/>
                
                    <button type="submit" class="btn btn-success float-end mb-3">Agregar</button>
                   
                </form>
               <a class="btn btn-success float-end mb-3" asp-controller="Generos" asp-action="Index">Volver</a>
            </div>
        </div>

    </div>
</div>

MiniProyecto_Itla_TV+/Views/Generos/Delete.cshtml
@model Application.ViewModels.Generos.GuardarGenerosViewModel


<div class="row mb-3">

    <h2 class="text-center nav-link text-white fw-bold"> Eliminar Genero </h2>
  
</div>

<div class="row mb-3">
    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>Esta seguro que desea eliminar el Genero @Model.Nombre?</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Generos" asp-action="DeletePost">                 

                    <input type="hidden" asp-for="Id" />

                    <a asp-controller="Generos" asp-action="Index" class="btn btn-primary">Volver atras</a>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>

MiniProyecto_Itla_TV+/Views/Generos/Index.cshtml
@* Strong type views *@
@model List<Application.ViewModel.Generos.GenerosViewModel>


<div class="row mb-3">

    <h2 class="text-center nav-link text-dark fw-bold"> Mantenimiento De Generos </h2>
  

</div>

<div class="row align-content-center">
    <div class="col-4 offset-4">
       
        <div class="card">
            <div class="card-header bg-dark text-light">
                Lista de Generos
                  <div class="text-end">
        <a class="btn btn-success float-end" asp-controller="Generos" asp-action="Create">Nuevo Genero</a>
    </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>                         
                            <th scope="col">Id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Nombre</td>
                             <td>
    <a class="btn btn-primary btn-edit" asp-controller="Generos" asp-action="Edit" asp-route-id="@item.Id">
        <i class="fa-solid fa-pen-to-square"></i>
    </a>
      </td>
     <td>
      
        <a asp-controller="Generos" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
            <i class="fa-solid fa-eraser"></i>
      </a>
    
    </td>
           </tr>    
                                                   
                        }
                       
                    </tbody>
                </table>
            </div>
        </div>
        <script src="https://kit.fontawesome.com/47ea8ef61d.js" crossorigin="anonymous"></script>
    </div>
</div>

MiniProyecto_Itla_TV+/Views/Home/Index.cshtml
@using Application.ViewModel.Productoras
@using Application.ViewModel.Series
@model List<Application.ViewModel.Series.SeriesViewModel>

<div class="container-fluid"> 
    
    <div class="row mb-3">
  
        <div class="col-md-6">

        <div class="card">
            <div class="card-header bg-dark text-light">
                <h4>Filtrar por Nombre</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Home" asp-action="Index">
                    <div class="form-group">
                        <label for="nombre-serie">Nombre de la Serie</label>
                        <input type="text" class="form-control" id="nombre-serie" name="NombreSerie" placeholder="Escriba el nombre de la serie">
                    </div>
                    <button type="submit" class="btn btn-success mb-3">Filtrar por Nombre</button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-light">
                <h4>Filtrar por Productora</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Home" asp-action="Index">
                    <div class="form-group">
                        <label for="productora-selector">Seleccionar Productora</label>
                        <select class="form-control" id="productora-selector" name="ProductoraId">
                            <option value="null">Todas</option>
                            @foreach(ProductorasViewModel productora in ViewBag.Productoras)
                            {
                                <option value="@productora.Id">@productora.Nombre</option>
                            }
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success mb-3">Filtrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
 
    <h4 class="mb-3"> Series Disponibles </h4>

    <div class="row mb-3">
        @foreach(var item in Model){
        <div class="col-4 mb-3">
          <div class="card shadow-sm">
    
              <img src="@item.Imagen" class="img-product-size bd-placeholder-img card-img-top " />
      
            <div class="card-body">
                <h4>@item.Nombre </h4>
                
              <p class="card-text">Genero Primario: @item.SeriesGeneros[0].ToString() </p>
                
              @if(@item.SeriesGeneros.Count >= 2){
              <p class="card-text">Genero Secundario: @item.SeriesGeneros[1].ToString() </p>
              } 
               <p class="card-text">Productora: @item.NombreProductora</p>
              <div>
                  <div class="btn-group">
                 <a class="btn btn-success " asp-controller="Home" asp-action="Video" asp-route-id="@item.Id">Detalles de la Serie</a>
                </div>
              </div>
            </div>
          </div>
        </div>
}
          </div>
        </div>

       
        
      
      </div>


</div>

<style> 

.card img{

    width: 100%;
    height: 300px;
    object-fit: cover;
}


</style> 

MiniProyecto_Itla_TV+/Views/Home/Video.cshtml
@model Application.ViewModels.Series.GuardarSeriesViewModel



<div class="row mb-3"> 
    
  <h2 class="text-center nav-link text-black fw-bold"> Trailer de @Model.Nombre </h2>

  <iframe width="560" height="600" src="@Model.Enlace" title="YouTube video player" frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

   <a asp-controller="Home" asp-action="Index" class="btn btn-success">Volver atras</a>
</div> 

MiniProyecto_Itla_TV+/Views/Productoras/Create.cshtml
@model Application.ViewModels.Productoras.GuardarProductorasViewModel 
@{
    bool modoEditar = Model.Id == 0 ? true : false;
  
}
<div class="row mb-3">

    <h2 class="text-center"> Mantenimiento de Productoras  </h2>
</div>

<div class="row">
    <div class="col-4 offset-4">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>@(modoEditar ? "Creando una productora" : $"Editando productora: {Model.Nombre}")</h4>
            </div>
            <div class="card-body">

                <form method="POST"  asp-controller="Productoras" asp-action="@(modoEditar ? "Create" : "EditPost")">
                    
                    
                    <div class="mb-3">
                        <label class="form-label">Nombre de Productora</label>
                        <input asp-for="Nombre" type="text" class="form-control mb-3" />  
                        <span class="text-danger"asp-validation-for="Nombre"> </span>
                    </div>
                    
                
                    <input type="hidden" asp-for="Id"/>
                
                    <button type="submit" class="btn btn-success float-end mb-3">Agregar</button>
                   
                </form>
               <a class="btn btn-success float-end mb-3" asp-controller="Productoras" asp-action="Index">Volver</a>
            </div>
        </div>

    </div>
</div>

MiniProyecto_Itla_TV+/Views/Productoras/Delete.cshtml
@model Application.ViewModels.Productoras.GuardarProductorasViewModel


<div class="row mb-3">

    <h2 class="text-center nav-link text-white fw-bold"> Eliminar Productora </h2>
  
</div>

<div class="row mb-3">
    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>Esta seguro que desea eliminar la Productora @Model.Nombre?</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Productoras" asp-action="DeletePost">                 

                    <input type="hidden" asp-for="Id" />

                    <a asp-controller="Productoras" asp-action="Index" class="btn btn-primary">Volver atras</a>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>

MiniProyecto_Itla_TV+/Views/Productoras/Index.cshtml
@* Strong type views *@
@model List<Application.ViewModel.Productoras.ProductorasViewModel>


<div class="row mb-3">

    <h2 class="text-center nav-link text-dark fw-bold"> Mantenimiento De Productoras </h2>
  

</div>

<div class="row align-content-center">
    <div class="col-4 offset-4">
       
        <div class="card">
            <div class="card-header bg-dark text-light">
                Lista de Productoras
                  <div class="text-end">
        <a class="btn btn-success float-end" asp-controller="Productoras" asp-action="Create">Nueva Productora</a>
    </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>                         
                            <th scope="col">Id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Nombre</td>
                             <td>
    <a class="btn btn-primary btn-edit" asp-controller="Productoras" asp-action="Edit" asp-route-id="@item.Id">
        <i class="fa-solid fa-pen-to-square"></i>
    </a>
      </td>
     <td>
      
        <a asp-controller="Productoras" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
            <i class="fa-solid fa-eraser"></i>
      </a>
    
    </td>
           </tr>    
                                                   
                        }
                       
                    </tbody>
                </table>
            </div>
        </div>
        <script src="https://kit.fontawesome.com/47ea8ef61d.js" crossorigin="anonymous"></script>
    </div>
</div>

MiniProyecto_Itla_TV+/Views/Series/Create.cshtml
@model Application.ViewModels.Series.GuardarSeriesViewModel 
@{
    bool modoEditar = Model.Id == 0 ? true : false;
  
}
<div class="row mb-3">

    <h2 class="text-center"> Mantenimiento de Series  </h2>
</div>

<div class="row">
    <div class="col-4 offset-4">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>@(modoEditar ? "Creando una Serie" : $"Editando Serie: {Model.Nombre}")</h4>
            </div>
            <div class="card-body">

                <form method="POST"  asp-controller="Series" asp-action="@(modoEditar ? "Create" : "EditPost")">
                    
                    
                    <div class="mb-3">
                        <label class="form-label">Nombre de Serie</label>
                        <input asp-for="Nombre" type="text" class="form-control mb-3" /> 
                        <span class="text-danger"asp-validation-for="Nombre"> </span>
                    </div>

                     <div class="mb-3">
                        <label class="form-label">URL de la imagen</label>
                        <input asp-for="Imagen" type="text" class="form-control mb-3"  /> 
                        <span class="text-danger"asp-validation-for="Imagen"> </span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Enlace de Video</label>
                        <input asp-for="Enlace" type="text" class="form-control mb-3" />  
                        <span class="text-danger"asp-validation-for="Enlace"> </span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="ProductoraId"class="form-label">Productora</label>
                        
                        <select asp-for="ProductoraId" asp-items="@(new SelectList(Model.Productoras, "Id", "Nombre"))" type="number" class="form-select mb-3" > 
                              <option value="0">Seleccione una Productora</option>
               
                        </select>
                        <span asp-validation-for="ProductoraId" class="text-danger"> </span>
                    </div>

                     <div class="mb-3">
                        <label asp-for="GeneroId1"class="form-label">Genero Primario</label>
                        
                        <select asp-for="GeneroId1" asp-items="@(new SelectList(Model.Generos, "Id","Nombre"))" type="number" class="form-select mb-3" > 
                              <option value="0">Seleccione un Genero</option>
               
                        </select>
                        <span asp-validation-for="GeneroId1" class="text-danger"> </span>
                    </div>

                     <div class="mb-3">
                        <label asp-for="GeneroId2"class="form-label">Genero Secundario</label>
                       
                        <select asp-for="GeneroId2" asp-items="@(new SelectList(Model.Generos, "Id","Nombre"))" type="number" class="form-select mb-3" > 
                              <option value="0">Seleccione un Genero</option>
               
                        </select>
                        <span asp-validation-for="GeneroId2" class="text-danger"> </span>
                    </div>
                    
                    
                
                    <input type="hidden" asp-for="Id"/>
                
                    <button type="submit" class="btn btn-success float-end mb-3">Agregar</button>
                   
                </form>
               <a class="btn btn-success float-end mb-3" asp-controller="Series" asp-action="Index">Volver</a>
            </div>
        </div>

    </div>
</div>

MiniProyecto_Itla_TV+/Views/Series/Delete.cshtml
@model Application.ViewModels.Series.GuardarSeriesViewModel


<div class="row mb-3">

    <h2 class="text-center nav-link text-white fw-bold"> Eliminar Productora </h2>
  
</div>

<div class="row mb-3">
    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header bg-success text-light">
                <h4>Esta seguro que desea eliminar la Serie @Model.Nombre?</h4>
            </div>
            <div class="card-body">
                <form method="post" asp-controller="Series" asp-action="DeletePost">                 

                    <input type="hidden" asp-for="Id" />

                    <a asp-controller="Series" asp-action="Index" class="btn btn-primary">Volver atras</a>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>

MiniProyecto_Itla_TV+/Views/Series/Index.cshtml
@model List<Application.ViewModel.Series.SeriesViewModel>

<div class ="container-fluid"> 

      <div class="row mb-3">

   <h2 class="text-center nav-link text-dark fw-bold"> Mantenimiento De Series </h2>
  <div class="col-3 offset-9">
                            <a class="btn btn-success" asp-controller="Series" asp-action="Create">Agregar Nueva Serie</a>
               </div>
     </div>

     <div class="row">
       
        @foreach(var item in Model){
        <div class="col-4 mb-3">
          <div class="card shadow-sm">
    
              <img src="@item.Imagen" class="img-product-size bd-placeholder-img card-img-top " />
      
            <div class="card-body">
                <h4>@item.Nombre </h4>
              <p class="card-text">Genero Primario: @item.SeriesGeneros[0].ToString() </p>
             
              @if(@item.SeriesGeneros.Count >= 2){
              <p class="card-text">Genero Secundario: @item.SeriesGeneros[1].ToString() </p>
              }
               <p class="card-text">Productora: @item.NombreProductora</p>
              
              <div>
                  <div class="btn-group">
                  
                      <a class="btn btn-primary btn-edit" asp-controller="Series" asp-action="Edit" asp-route-id="@item.Id">
        <i class="fa-solid fa-pen-to-square"></i>
    </a>
                    <a asp-controller="Series" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
            <i class="fa-solid fa-eraser"></i>
      </a>
                 
                </div>
              </div>
            </div>
          </div>
        </div>
      
    }
          </div>
          
        </div>

       
        
      <script src="https://kit.fontawesome.com/47ea8ef61d.js" crossorigin="anonymous"></script>
      </div>


</div>

<style> 

.card img{

    width: 100%;
    height: 300px;
    object-fit: cover;
}


</style> 

MiniProyecto_Itla_TV+/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniProyecto_Itla_TV_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiniProyecto_Itla_TV_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <nav class="navbar bg-success navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-fluid">
    <a class="navbar-brand text-dark fw-bold" href="#">Prime TV</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ml-2">
                            <a class="nav-link text-white fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item ml-2">
                            <a class="nav-link   text-white fw-bold" asp-area="" asp-controller="Series" asp-action="Index">Series</a>
                        </li>

                        <li class="nav-item ml-2">
                            <a class="nav-link   text-white fw-bold" asp-area="" asp-controller="Productoras" asp-action="Index">Productoras</a>
                        </li>

                        <li class="nav-item ml-2">
                          <a class="nav-link text-white fw-bold"  asp-area="" asp-controller="Generos" asp-action="Index">Generos</a>
                        </li>
            </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>